### ISSUE TITLE
Playground not using latest master?

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/playground-lingua-franca#100]
The CI in the playground does not appear to use the latest master.
The compile failures reported [here](https://github.com/lf-lang/playground-lingua-franca/actions/runs/7936677142) do not occur with lingua-franca/master.

**Comment by lhstrh** [comment]
It's not -- it's using the latest release.

**Comment by lhstrh** [comment]
Shall we do a patch release?

**Comment by edwardalee** [comment]
Hmm… Where we are is not a patch.
Recall we removed all the deprecated functions…

Edward

**Comment by lhstrh** [comment]
Up to us what we want to include in a patch. We can just cherry-pick from
master on the release branch…
