### ISSUE TITLE
command 'klighd-vscode.diagram.open' not found

### ISSUE THREAD

**Issue by akihitoiwai0912** [lf-lang/playground-lingua-franca#72]
Container creation is done successfully. But the button of 'Open in Diagram' does not work with bellow error message.

`command 'klighd-vscode.diagram.open' not found`

In addition, Java 11 is installed as default version. So I needed to install Java 17 manually.

```
@akihitoiwai0912 ➜ /workspaces/playground-lingua-franca (main) $ java --version
openjdk 11.0.19 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing)
```

**Comment by lhstrh** [comment]
I'm finding the exact same problems as I'm trying it out as well :-) We'll get this sorted out... The Codespaces setup is rather finicky. Have you tried the GitPod version yet?

**Comment by akihitoiwai0912** [comment]
Not yet. I will get it try!

**Comment by lhstrh** [comment]
I just did! It appears to work flawlessly. Please report any issue you may find :-)

**Comment by akihitoiwai0912** [comment]
Oh! It works too. No problem on GidPod. In cace of codespaces, Ctrl-Shift-P command did not work well.

**Comment by lhstrh** [comment]
I think it is browser dependent what key strokes are allowed. In my firefox, I have to use <kbd>F1</kbd> to get the command palette.

**Comment by lhstrh** [comment]
I looks like these problems are now solved.
